# Generated by Django 4.2.6 on 2023-10-17 16:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathnews', '0004_mathnewsuser_delete_mathnews_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MathNewsUser',
        ),
        migrations.RemoveField(
            model_name='mathnews',
            name='paragraph3',
        ),
        migrations.AddField(
            model_name='mathnews',
            name='is_authorized',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mathnews',
            name='author',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='mathnews',
            name='paragraph1',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='mathnews',
            name='paragraph2',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='mathnews',
            name='timeline',
            field=models.DateField(default=datetime.date(2023, 10, 17)),
        ),
    ]
