# Generated by Django 4.2.6 on 2023-10-18 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mathnews', '0007_alter_mathnews_heading_alter_mathnews_paragraph1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mathnews',
            old_name='is_authorized',
            new_name='validate',
        ),
    ]
