# Generated by Django 4.2.6 on 2023-10-18 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mathnews', '0008_rename_is_authorized_mathnews_validate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MathNews',
            new_name='TechNews',
        ),
    ]
