# Generated by Django 4.2.6 on 2023-10-25 22:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mathnews', '0010_alter_technews_paragraph1_alter_technews_paragraph2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='technews',
            old_name='paragraph1',
            new_name='part_1',
        ),
        migrations.RenameField(
            model_name='technews',
            old_name='paragraph2',
            new_name='part_2',
        ),
        migrations.AddField(
            model_name='technews',
            name='cloud',
            field=models.ManyToManyField(related_name='dislike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='technews',
            name='star',
            field=models.ManyToManyField(related_name='like', to=settings.AUTH_USER_MODEL),
        ),
    ]
