# Generated by Django 4.2.6 on 2023-10-26 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mathnews', '0011_rename_paragraph1_technews_part_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technews',
            name='cloud',
            field=models.ManyToManyField(related_name='cloud', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='technews',
            name='star',
            field=models.ManyToManyField(blank=True, default=None, related_name='star', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('Like', 'Like'), ('Unlike', 'Unlike')], default='star', max_length=10)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mathnews.technews')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
