# Generated by Django 4.2.6 on 2023-10-26 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathnews', '0012_alter_technews_cloud_alter_technews_star_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='value',
            field=models.CharField(choices=[('Star', 'Star'), ('Unstar', 'Unstar')], default='star', max_length=10),
        ),
    ]
